language: node_js

node_js:
- node

before_deploy:
  - cd backend/express
install:
  - cd backend/express && npm install && cd .. && cd ..
script:
  - cd backend/express
  - ln -s knexfile_travis.js knexfile.js
  - node node_modules/knex/bin/cli.js migrate:latest
  - node node_modules/knex/bin/cli.js seed:run
  - npm test
